param(
    [string]$CerealInclude,
    [string]$VisualStudioPath,
    [switch]$DownloadCereal
)

$ErrorActionPreference = 'Stop'
$fixtureDirectory = $PSScriptRoot
$repositoryRoot = [IO.Path]::GetFullPath((Join-Path $fixtureDirectory '../../../..'))
$buildDirectory = Join-Path $repositoryRoot 'build/tools/native-fixtures'
New-Item -ItemType Directory -Force -Path $buildDirectory | Out-Null

$cerealVersion = '1.3.2'
$cerealUrl = 'https://github.com/USCiLab/cereal/archive/refs/tags/v1.3.2.zip'
$cerealArchiveHash = 'E72C3FA8FE3D531247773E346E6824A4744CC6472A25CF9B30599CD52146E2AE'
if (-not $CerealInclude) {
    $CerealInclude = Join-Path $buildDirectory "cereal-$cerealVersion/include"
}
if (-not (Test-Path -LiteralPath (Join-Path $CerealInclude 'cereal/cereal.hpp'))) {
    if (-not $DownloadCereal) {
        throw 'Pass -CerealInclude with existing cereal headers, or -DownloadCereal to fetch the pinned official archive.'
    }
    $archivePath = Join-Path $buildDirectory "cereal-$cerealVersion.zip"
    Invoke-WebRequest -Uri $cerealUrl -OutFile $archivePath
    if ((Get-FileHash -LiteralPath $archivePath -Algorithm SHA256).Hash -ne $cerealArchiveHash) {
        throw 'The official cereal archive did not match the pinned SHA256.'
    }
    Expand-Archive -LiteralPath $archivePath -DestinationPath $buildDirectory -Force
}

function Read-RepositoryFile([string]$Path) {
    return [IO.File]::ReadAllText((Join-Path $repositoryRoot $Path))
}

function Get-BracedDeclaration([string]$Source, [string]$StartPattern, [bool]$IncludeSemicolon = $true) {
    $start = [regex]::Match($Source, $StartPattern)
    if (-not $start.Success) { throw "Declaration not found: $StartPattern" }
    $opening = $Source.IndexOf('{', $start.Index)
    if ($opening -lt 0) { throw "Declaration has no opening brace: $StartPattern" }
    # Skip comments and quoted literals, so their braces cannot change nesting.
    $tokens = [regex]::Matches($Source.Substring($opening), '(?s)/\*.*?\*/|//[^\r\n]*|"(?:\\.|[^"\\])*"|''(?:\\.|[^''\\])*''|[{}]')
    $depth = 0
    foreach ($token in $tokens) {
        if ($token.Value -eq '{') { $depth++ }
        elseif ($token.Value -eq '}') {
            $depth--
            if ($depth -eq 0) {
                $end = $opening + $token.Index + 1
                if ($IncludeSemicolon) {
                    $semicolon = [regex]::Match($Source.Substring($end), '^\s*;')
                    if (-not $semicolon.Success) { throw "Declaration has no terminal semicolon: $StartPattern" }
                    $end += $semicolon.Length
                }
                return $Source.Substring($start.Index, $end - $start.Index)
            }
        }
    }
    throw "Unbalanced declaration: $StartPattern"
}

function Get-ActionData([string]$Source) {
    $start = [regex]::Match($Source, '\bstruct Params\b')
    $end = [regex]::Match($Source.Substring($start.Index), '\bprivate\s*:')
    if (-not $start.Success -or -not $end.Success) { throw 'Cannot locate action data declarations.' }
    return $Source.Substring($start.Index, $end.Index)
}

$pushPath = 'IntelPresentMon/KernelProcess/kact/PushSpecification.h'
$introPath = 'IntelPresentMon/KernelProcess/kact/Introspect.h'
$openPath = 'IntelPresentMon/KernelProcess/kact/OpenSession.h'
$hotkeyPath = 'IntelPresentMon/KernelProcess/kact/BindHotkey.h'
$overlayPath = 'IntelPresentMon/Core/source/kernel/OverlaySpec.h'
$enumsPath = 'IntelPresentMon/Core/source/gfx/layout/Enums.h'
$enumUtilsPath = 'IntelPresentMon/Core/source/gfx/layout/EnumUtils.h'
$push = Read-RepositoryFile $pushPath
$pushData = Get-BracedDeclaration $push '\bnamespace push_spec_impl\b' $false
$colorSerialize = Get-BracedDeclaration $push '\bnamespace cereal\b' $false
$overlayEnum = Get-BracedDeclaration (Read-RepositoryFile $overlayPath) '\benum class OverlayPosition\b'
$enumUtils = Read-RepositoryFile $enumUtilsPath
$macroStart = $enumUtils.IndexOf('#define XEN_KEY_TEM')
$macroEnd = $enumUtils.IndexOf('#define XEN_PARSE_TEM', $macroStart)
if ($macroStart -lt 0 -or $macroEnd -lt 0) { throw 'Cannot locate native enum generator macros.' }
$enumMacros = $enumUtils.Substring($macroStart, $macroEnd - $macroStart)
$enums = Read-RepositoryFile $enumsPath
$axisStart = $enums.IndexOf('#define XEN_LIST_AXIS_AFFINITY')
$axisEnd = $enums.IndexOf('XEN_GENERATE_REGISTRY(AxisAffinity', $axisStart)
if ($axisStart -lt 0 -or $axisEnd -lt 0) { throw 'Cannot locate native axis enum declaration.' }
$axisEnum = $enums.Substring($axisStart, $axisEnd - $axisStart)
$introData = Get-ActionData (Read-RepositoryFile $introPath)
$openData = Get-ActionData (Read-RepositoryFile $openPath)
$hotkeyData = Get-ActionData (Read-RepositoryFile $hotkeyPath)

$generatedHeader = @"
// Generated by NativeFixtures/Generate.ps1; do not edit.
// Declarations and serialization bodies below are extracted verbatim from repository headers.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <optional>
#include <variant>
#include <cereal/cereal.hpp>
#include <cereal/types/string.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/array.hpp>
#include <cereal/types/optional.hpp>
#include <cereal/types/variant.hpp>
#include "IntelPresentMon/Interprocess/source/act/Packet.h"
#include "IntelPresentMon/PresentMonAPI2/PresentMonAPI.h"
#include "IntelPresentMon/Core/source/gfx/base/Geometry.h"

$enumMacros
namespace p2c::gfx::lay {
$axisEnum
}
#undef XEN_LIST_AXIS_AFFINITY
#undef XEN_GENERATE_ENUM
#undef XEN_KEY_TEM
namespace p2c::kern {
struct OverlaySpec {
$overlayEnum
};
}
namespace kproc::kact {
using ::p2c::gfx::Color;
$pushData
}
$colorSerialize
namespace native_fixture {
struct Introspect {
$introData
};
struct OpenSession {
$openData
};
struct BindHotkey {
$hotkeyData
};
}
"@
[IO.File]::WriteAllText((Join-Path $buildDirectory 'NativeTypes.generated.h'), $generatedHeader, [Text.UTF8Encoding]::new($false))

if (-not $VisualStudioPath -and -not (Get-Command cl.exe -ErrorAction SilentlyContinue)) {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio/Installer/vswhere.exe'
    $VisualStudioPath = & $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if ($LASTEXITCODE -ne 0 -or -not $VisualStudioPath) { throw 'No Visual Studio C++ tools installation found.' }
}
if ($VisualStudioPath) {
    & (Join-Path $VisualStudioPath 'Common7/Tools/Launch-VsDevShell.ps1') -Arch amd64 -HostArch amd64 -SkipAutomaticLocation -NoLogo
}
$executable = Join-Path $buildDirectory 'native-fixtures.exe'
$objectFile = Join-Path $buildDirectory 'native-fixtures.obj'
& cl.exe /nologo /std:c++20 /EHsc /W4 /MD "/I$repositoryRoot" "/I$CerealInclude" "/I$buildDirectory" "/Fo$objectFile" "/Fe$executable" (Join-Path $fixtureDirectory 'Generate.cpp')
if ($LASTEXITCODE -ne 0) { throw "Native fixture build failed: $LASTEXITCODE" }
Write-Output 'Native fixture build succeeded.'
& $executable $fixtureDirectory generate
if ($LASTEXITCODE -ne 0) { throw "Native fixture generation failed: $LASTEXITCODE" }
# Verification is deliberately after the successful native build.
& $executable $fixtureDirectory verify
if ($LASTEXITCODE -ne 0) { throw "Native fixture verification failed: $LASTEXITCODE" }

$sourcePaths = @(
    $pushPath, $introPath, $openPath, $hotkeyPath, $overlayPath, $enumsPath, $enumUtilsPath,
    'IntelPresentMon/Interprocess/source/act/Packet.h',
    'IntelPresentMon/PresentMonAPI2/PresentMonAPI.h',
    'IntelPresentMon/Core/source/gfx/base/Geometry.h',
    'IntelPresentMon/CommonUtilities/pipe/Pipe.h'
)
$provenance = [ordered]@{
    cerealVersion = $cerealVersion
    cerealSource = $cerealUrl
    cerealArchiveSha256 = $cerealArchiveHash
    compiler = (Get-Item -LiteralPath (Get-Command cl.exe).Source).VersionInfo.FileVersion
    platform = 'Windows x64, little-endian'
    framing = 'uint32 body byte count; cereal BinaryOutputArchive(PacketHeader, payload)'
    sourceHeaders = @($sourcePaths | ForEach-Object {
        [ordered]@{ path = $_; sha256 = (Get-FileHash -LiteralPath (Join-Path $repositoryRoot $_) -Algorithm SHA256).Hash }
    })
    fixtures = @(Get-ChildItem -LiteralPath $fixtureDirectory -Filter '*.bin' | Sort-Object Name | ForEach-Object {
        [ordered]@{ file = $_.Name; bytes = $_.Length; sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash }
    })
}
[IO.File]::WriteAllText((Join-Path $fixtureDirectory 'manifest.json'), ($provenance | ConvertTo-Json -Depth 8), [Text.UTF8Encoding]::new($false))
