<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros">
    <VersionPropsImported>true</VersionPropsImported>
    <!-- PresentMonVersion should be "dev" on main branch, and the version number (e.g., 2.1.0) on release branches. -->
    <PresentMonVersion Condition="'$(PresentMonVersion)'==''">2.6.0</PresentMonVersion>
    <PresentMonFileVersion Condition="'$(PresentMonFileVersion)'==''">2.6.0.2</PresentMonFileVersion>
    <PresentMonProductVersion Condition="'$(PresentMonProductVersion)'==''">$(PresentMonFileVersion)</PresentMonProductVersion>
    <PresentMonCopyright Condition="'$(PresentMonCopyright)'==''">Copyright (C) 2017-$([System.DateTime]::UtcNow.Year)</PresentMonCopyright>
  </PropertyGroup>
  <PropertyGroup>
    <PresentMonFileVersionNumbers Condition="'$(PresentMonFileVersionNumbers)'==''">$([System.String]::Copy("$(PresentMonFileVersion)").Replace('.', ','))</PresentMonFileVersionNumbers>
    <PresentMonProductVersionNumbers Condition="'$(PresentMonProductVersionNumbers)'==''">$([System.String]::Copy("$(PresentMonProductVersion)").Replace('.', ','))</PresentMonProductVersionNumbers>
  </PropertyGroup>
</Project>
